# Generated by Django 5.0.6 on 2024-06-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sys_created_on", models.DateTimeField(auto_now_add=True)),
                ("sys_updated_on", models.DateTimeField(auto_now=True)),
                ("sys_id", models.CharField(blank=True, max_length=64, unique=True)),
                ("attendees", models.JSONField()),
                ("meeting_date", models.DateTimeField()),
                ("meeting_topic", models.CharField(max_length=100)),
                ("meeting_start_time", models.DateTimeField()),
                ("meeting_end_time", models.DateTimeField()),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="MeetingProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sys_created_on", models.DateTimeField(auto_now_add=True)),
                ("sys_id", models.CharField(blank=True, max_length=64, unique=True)),
                ("content", models.JSONField()),
                (
                    "meeting_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_protocols",
                        to="database.meetingcall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.JSONField()),
                ("sys_id", models.CharField(blank=True, max_length=64, unique=True)),
                ("call_id", models.CharField(max_length=50)),
                ("caller_id", models.CharField(max_length=50)),
                ("sys_created_on", models.DateTimeField(auto_now_add=True)),
                ("payload", models.FileField(upload_to="audio/")),
                ("transcription", models.TextField()),
                (
                    "meeting_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_records",
                        to="database.meetingcall",
                    ),
                ),
                (
                    "meeting_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_records",
                        to="database.meetingprotocol",
                    ),
                ),
            ],
        ),
    ]
