# Generated by Django 5.0.6 on 2024-06-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_callrecord_meeting_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrecord",
            name="meeting_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.meetingcall",
            ),
        ),
    ]
