# Generated by Django 5.0.6 on 2024-06-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_callrecord_meeting_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingprotocol",
            name="meeting_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_protocols",
                to="database.meetingcall",
            ),
        ),
    ]
